version: '3'
services:   
  jupyter:
    build:
      context: ./.containers/jupyter/
      dockerfile: Dockerfile
      args:
        WORK_DIR: ${WORK_DIR}
        MLFLOW_PORT: ${MLFLOW_PORT}
    container_name: ${COMPOSE_PROJECT_NAME}-lab
    command: > 
      jupyter lab 
      --ip=0.0.0.0 
      --port=${JUPYTER_PORT}
      --allow-root
      --no-browser
      --NotebookApp.token="${JUPYTER_TOKEN}"
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    restart: always
    volumes:
      - ./projects:${WORK_DIR}
      - ${MOUNT_DIR}:${WORK_DIR}/data/mnt
    working_dir: ${WORK_DIR}
  
